packer {
  required_version = ">= 0.12.0"
}

variable "client_id" {
  type    = string
  default = "${env("ARM_CLIENT_ID")}"
}

variable "client_secret" {
  type    = string
  default = "${env("ARM_CLIENT_SECRET")}"
}

variable "resource_group_name" {
  type = string
}

variable "subscription_id" {
  type    = string
  default = "${env("ARM_SUBSCRIPTION_ID")}"
}

variable "tenant_id" {
  type    = string
  default = "${env("ARM_TENANT_ID")}"
}

source "azure-arm" "autogenerated_1" {
  client_id                         = "${var.client_id}"
  client_secret                     = "${var.client_secret}"
  image_offer                       = "UbuntuServer"
  image_publisher                   = "Canonical"
  image_sku                         = "16.04.0-LTS"
  managed_image_name                = "vault-consul-ubuntu"
  managed_image_resource_group_name = "${var.resource_group_name}"
  build_resource_group_name         = "${var.resource_group_name}"
  os_type                           = "Linux"
  subscription_id                   = "${var.subscription_id}"
  tenant_id                         = "${var.tenant_id}"
  vm_size                           = "Standard_DS2_v2"
  shared_image_gallery_destination {
    subscription = "${var.subscription_id}"
    resource_group = "${var.resource_group_name}"
    gallery_name = "sig_jared_holgate"
    image_name = "azure-vault"
    image_version = "1.0.0"
    replication_regions = [ "UK South" ]
  }
}

build {
  sources = ["source.azure-arm.autogenerated_1"]

  provisioner "shell" {
    execute_command = "chmod +x {{ .Path }}; {{ .Vars }} sudo -E sh '{{ .Path }}'"
    inline          = [ 
      "DEBIAN_FRONTEND=noninteractive apt-get -y upgrade", 
      "echo \"deb https://packages.microsoft.com/repos/azure-cli/ wheezy main\" | sudo tee /etc/apt/sources.list.d/azure-cli.list", 
      "apt-key adv --keyserver packages.microsoft.com --recv-keys 417A0893", 
      "apt-get update && apt-get install -y git libssl-dev libffi-dev python-dev build-essential apt-transport-https azure-cli",

      "curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -", 
      "sudo apt-add-repository \"deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main\"",
      "sudo apt-get update && sudo apt-get install vault"
    ]
    inline_shebang  = "/bin/sh -x"
  }
}
