name: Packer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: ./packer/vault_vm.pkr.hcl

      - name: Set Variables
        run: |
          echo 'client_id="${{ secrets.BUILD_ARM_CLIENT_ID }}"' >> variables.pkrvars.hcl
          echo 'client_secret="${{ secrets.BUILD_ARM_CLIENT_SECRET }}"' >> variables.pkrvars.hcl
          echo 'subscription_id="${{ secrets.BUILD_ARM_SUBSCRIPTION_ID }}"' >> variables.pkrvars.hcl
          echo 'tenant_id="${{ secrets.BUILD_ARM_TENANT_ID }}"' >> variables.pkrvars.hcl
          echo 'resource_group_name="azure-vault-build"' >> variables.pkrvars.hcl
          echo '' >> variables.pkrvars.hcl

      - name: Build Artifact
        uses: hashicorp/packer-github-actions@master
        with:
          command: build
          arguments: "-on-error=abort"
          target: ./packer/vault_vm.pkr.hcl
        env:
          PACKER_LOG: 1
